default:
  #--------------------------------------------------------------------------------------------------------------------
  # Setting path and local variables
  #--------------------------------------------------------------------------------------------------------------------
  # v1) Name for your center
  organization_name: "meDIC_StandortName"
  
  # v2) set the path to input data 
  # replace this with the URL of your FHIR server
  path: "http://141.5.101.1:8080/fhir/" #Airolo server
  # CSV and XLSX file formats are also supported
  # path: "./Data/medData/dqTestData.csv"
  #path: "./Data/medData/dqTestData.xlsx"
  
  # v3) set proxy and access configuration if required
  # set your username and password if you need to authenticate on your fhir server
  username: NULL
  password: NULL	
  # set your token or path to r-script, if your fhir server needs token authentification.
  token: NULL
  # set these parameters if you need to use a proxy server (e.G. http://proxy:port )
  http_proxy: NULL
  https_proxy: NULL
  # set the fhir server adress here, if you need to bypass the proxy for accessing it locally
  no_proxy: NULL
  
  # v4) set the number of inpatient case for each year
  inpatientCases_number: !expr list ("2015"=800, "2016"=900, "2017"=940, "2018"=950, "2019"=990,  "2020"=997, "2021"=999, "2022"=1000)
  
  # v5) if the standard code for inpatient cases "IMP" is available uncomment the below line or replace it by local code else default = NULL
  inpatientEncounter_code: NULL
  #inpatientEncounter_code: "IMP"
  
  #--------------------------------------------------------------------------------------------------------------------
  # Please change the variables v5 - v10 only if technical or legal restrictions otherwise prevent successful execution!
  #--------------------------------------------------------------------------------------------------------------------
  # v6) set the start and end of the reporting period
  startYear: 2015
  endYear: 2022
  
  # v7) set the date format and the data item for diagnosis recorded date
  # set the date format
  date_format: "%Y-%m-%d"
  #change default value for diagnosis recorded date if your local fhir server does not have "recordedDate" , e.g.,  "onsetDateTime"
  diagnosisDate_item: "recordedDate"
  
  # v8) set the fhir data variables
  # fhir path to the data item encounter class, change this path if your local fhir server does not have "class/code", e.g., "class/display"
  encounterClass_item: "class/code"
  #diagnosisUse_item
  diagnosisUse_item: "diagnosis/use/coding/code"
  # orpha system
  orphaCode_system: "http://www.orpha.net"
  # custom parameters for conditions resources on local fhir server
  # use 'http://fhir.de/CodeSystem/dimdi/icd-10-gm' or 'http://fhir.de/CodeSystem/bfarm/icd-10-gm' or custom
  icdCode_system: "http://fhir.de/CodeSystem/dimdi/icd-10-gm"
  # define the maximal bundles for fhir_search (), default value = Inf
  fhirBundles_max: "inf"
  # set the number of diagnosis codes per thread
  diagnosis_no: 25
  
  # v9) set the version of diagnosisList, e.g.,  'v1' or 'v2' default =  'v2'
  diagnosisList_version: "v2"
  
  # v10) set rules and references for data quality checks
  ageMax: 115
  alphaIdSe_reference: "./Data/refData/icd10gm2022_alphaidse_edvtxt.txt"
  tracerDiagnoses_refrence: "./Data/refData/Tracerdiagnosen_AlphaID-SE-2022.csv"



  
